21. Solve system of linear equations
22. Compute determinant
23. Find eigenvalues/eigenvectors
24. Normalize a vector
25. Compute cosine similarity
26. Compare loop vs vectorized speed
27. Implement gradient descent step
28. Create identity matrix
29. Compute covariance matrix
30. Simulate random sampling

In [5]:
import numpy as np

A = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

X = A[:, :-1]   # All rows, all columns except last
y = A[:, -1:]   # All rows, only last column (keep 2D shape)

s = np.linalg.solve(X, y)
print(s)
print(X @ s)


[[-1.]
 [ 2.]]
[[3.]
 [6.]]


In [4]:
A = np.array(
    [[1, 2, 3],
     [4, 10, 6],
     [7, 8, 9]]
)

s = np.linalg.det(A)
print(s)

-59.999999999999986


In [5]:
import numpy as np
A = np.array(
    [[1, 2, 3],
     [4, 10, 6],
     [7, 8, 9]]
)

values, vectors = np.linalg.eig(A)
print(values)    
print(vectors)

v = vectors[:, 1]
print(A @ v)
print(values[1] * v)


[18.04204166 -1.09079526  3.0487536 ]
[[-0.2051386  -0.81366495  0.2595975 ]
 [-0.64877001 -0.02083741 -0.71227282]
 [-0.73281351  0.58096055  0.65213232]]
[ 0.88754187  0.02272935 -0.63370901]
[ 0.88754187  0.02272935 -0.63370901]


In [8]:
A = np.array(
    [[1, 2, 3],
     [4, 10, 6],
     [7, 8, 9]]
)

norm = np.linalg.norm(A)
print(norm) 

A_unit = A / norm

print("Normalized:", A_unit)
print("Length:", np.linalg.norm(A_unit))


18.973665961010276
Normalized: [[0.05270463 0.10540926 0.15811388]
 [0.21081851 0.52704628 0.31622777]
 [0.36893239 0.42163702 0.47434165]]
Length: 1.0


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot = np.dot(a, b)

norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

cos_sim = dot / (norm_a * norm_b)

print("Cosine Similarity:", cos_sim)


Cosine Similarity: 0.9746318461970762


In [10]:
import time

arr = np.arange(1_000_000)

# Loop version
start = time.time()
result = []
for x in arr:
    result.append(x * 2)
print("Loop time:", time.time() - start)

# Vectorized version
start = time.time()
result2 = arr * 2
print("Vectorized time:", time.time() - start)


Loop time: 0.18630194664001465
Vectorized time: 0.002685546875


In [1]:
import numpy as np
# initial weights
w = np.array([2.0, 3.0])

# gradient
grad = np.array([1.0, 2.0])

learning_rate = 0.01

# update
w = w - learning_rate * grad

print("Updated weights:", w)


Updated weights: [1.99 2.98]


In [2]:
I = np.eye(3)

print(I)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

cov = np.cov(data)

print("Covariance matrix:\n", cov)


Covariance matrix:
 [[1. 1.]
 [1. 1.]]


In [4]:
# Uniform distribution
uniform = np.random.rand(5)

# Normal distribution
normal = np.random.randn(5)

# Random integers
rand_int = np.random.randint(0, 10, size=5)

print(uniform)
print(normal)
print(rand_int)


[0.99497193 0.21565292 0.33386523 0.08388851 0.57937268]
[-2.11990727 -1.66034815  0.3784827   1.24173696 -0.01913393]
[2 0 3 6 6]
