In [7]:
import math

word = input("Enter a word")
flag = True
for i in range(0, math.floor(len(word)/2)):
    if word[i] != word[(i+1)*-1]:
        flag = False

if flag:
    print("Number is Palindrome")
else:
    print("Number is not Palindrome")


Number is not Palindrome


In [10]:
sentance = input("Enter a sentance")
n_vowel = 0
for i in range(0,len(sentance)):
    if sentance[i] in ['a','e','i','o','u']:
        n_vowel+=1

print(n_vowel)

0


In [11]:
d = {"a": 1, "b": 2, "c": 1}
inv = {}

for k, v in d.items():
    inv.setdefault(v, []).append(k)

print(inv)

{1: ['a', 'c'], 2: ['b']}


In [12]:
scores = {"Ali": 85, "Emon": 92, "Sara": 78}

print(scores.items())

sorted_by_score = sorted(scores.items(), key=lambda x: x[1], reverse=True)
# print(sorted_by_score)

dict_items([('Ali', 85), ('Emon', 92), ('Sara', 78)])


In [13]:
import csv

# Writing CSV
with open("students.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Name", "Math", "Science"])
    writer.writerow(["Emon", 85, 90])
    writer.writerow(["Sara", 78, 82])

# Reading CSV
with open("students.csv", "r") as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)


['Name', 'Math', 'Science']
['Emon', '85', '90']
['Sara', '78', '82']


In [14]:
with open("students.csv", "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(row["Name"], row["Math"])

Emon 85
Sara 78


In [ ]:
import csv

with open("products.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow

In [19]:
import numpy as np

# Create 1D array
arr = np.array([1, 2, 3, 4, 5])
# print(arr)

# Create 2D array
arr2 = np.array([[1, 2], [3, 4]])
# print(arr2)
print(arr.ndim)


1


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     # element-wise addition
print(a * b)     # element-wise multiplication
print(a - b)
print(a / b)


[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [21]:
arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))       # average
print(np.median(arr))     # median
print(np.sum(arr))        # sum
print(np.min(arr), np.max(arr))
print(np.arange(0, 10, 2))  # create range array
print(np.linspace(0, 1, 5))  # evenly spaced numbers


3.0
3.0
15
1 5
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [22]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.shape)   # (2, 3)
print(matrix.ndim)    # 2D


[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)          # element-wise addition
print(A * B)          # element-wise multiplication
print(np.dot(A, B))   # matrix multiplication
print(A.T)            # transpose


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [24]:
arr = np.arange(1, 13)   # 1D array 1–12
print(arr.reshape(3, 4)) # 3 rows, 4 cols

matrix = np.array([[1,2,3],[4,5,6]])
flat = matrix.flatten()   # convert to 1D
print(flat)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4 5 6]


In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)  # B is broadcasted to each row


[[11 22 33]
 [14 25 36]]


In [29]:
arr = np.arange(1,7)
# print(arr.reshape(2,3))
arr = arr.reshape(2,3)
arr2 = np.array([10, 20, 30])

# print(arr+arr2)
# print(2*arr)
arr = arr.flatten()
print(arr.mean())

3.5


In [2]:
words = ["banana", "apple", "kiwi"]
words.sort(key=len)
print(words)

['kiwi', 'apple', 'banana']


In [ ]:
data = [(1,5), (2,3), (4,1)]

# def get_second(x):
#     return x[1]

# data.sort(key=get_second)

data.sort(key=lambda x: x[1])



In [ ]:
d = {"b":2, "a":1, "c":3}
sorted(d)
print(d)

['a', 'b', 'c']


In [9]:
funcs = [lambda x: x*i for i in range(3)]
print(funcs)

[<function <lambda> at 0x79a8a548fba0>, <function <lambda> at 0x79a8a548fb00>, <function <lambda> at 0x79a8a548f600>]


### Practice Tasks

1. Use lambda to square a list
2. Filter even numbers using `filter()`
3. Convert string list to int list using `map()`
4. Find max using `reduce()`
5. Zip two lists into dictionary
6. Enumerate list items with index
7. Write function using `*args`
8. Write function using `**kwargs`
9. Demonstrate shallow vs deep copy
10. Write decorator to log function calls

In [10]:
nums = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, nums))
print(squared)


[1, 4, 9, 16, 25]


In [11]:
nums = [1, 2, 3, 4, 5]
even_nums = list(filter(lambda x: x % 2 == 0, nums))
print(even_nums)

[2, 4]


In [12]:
str_nums = ["1", "2", "3", "4"]
int_nums = list(map(int, str_nums))
print(int_nums)

[1, 2, 3, 4]


In [13]:
from functools import reduce    

nums = [1, 2, 3, 4]
max_num = reduce(lambda x, y: x if x > y else y, nums)
print(max_num)


4


In [15]:
keys = ["name", "age", "city"]
values = ["Emon", 25, "Dhaka"]

result = dict(zip(keys, values))
print(result)  # {'name': 'Emon', 'age': 25, 'city': 'Dhaka'}


{'name': 'Emon', 'age': 25, 'city': 'Dhaka'}


In [16]:
fruits = ["apple", "banana", "kiwi"]

for index, fruit in enumerate(fruits, start=1):
    print(f"{index}. {fruit}")


1. apple
2. banana
3. kiwi


In [ ]:
def sum_all(*args):
    total = 0
    for num in args:
        total += num
    return total

print(sum_all(1, 2, 3, 4))  # 10


In [17]:
def print_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_info(name="Emon", age=25, city="Dhaka")


name: Emon
age: 25
city: Dhaka


In [18]:
import copy

original = [[1, 2], [3, 4]]

# Shallow copy
shallow = copy.copy(original)
shallow[0][0] = 99
print("Shallow:", original)  # [[99, 2], [3, 4]] → affected!

# Deep copy
original = [[1, 2], [3, 4]]
deep = copy.deepcopy(original)
deep[0][0] = 100
print("Deep:", original)  # [[1, 2], [3, 4]] → safe


Shallow: [[99, 2], [3, 4]]
Deep: [[1, 2], [3, 4]]


In [19]:
def log(func):
    def wrapper(*args, **kwargs):
        print(f"Calling function '{func.__name__}' with args={args} kwargs={kwargs}")
        result = func(*args, **kwargs)
        print(f"'{func.__name__}' returned {result}")
        return result
    return wrapper

@log
def add(a, b):
    return a + b

add(5, 7)


Calling function 'add' with args=(5, 7) kwargs={}
'add' returned 12


12

11. Create 1D, 2D, 3D arrays
12. Reshape arrays
13. Generate random arrays
14. Find mean, median, std
15. Element-wise operations
16. Matrix multiplication
17. Boolean masking
18. Replace values conditionally
19. Stack and split arrays
20. Flatten array


In [20]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4])
print("1D:", arr1d)

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D:\n", arr2d)

# 3D array
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D:\n", arr3d)


1D: [1 2 3 4]
2D:
 [[1 2 3]
 [4 5 6]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
arr = np.arange(1, 13)  # [1, 2, ..., 12]
print("Original:", arr)

arr2d = arr.reshape(3, 4)  # 3 rows, 4 columns
print("Reshaped 2D:\n", arr2d)

arr3d = arr.reshape(2, 2, 3)  # 3D: 2x2x3
print("Reshaped 3D:\n", arr3d)


# -1 can be used to auto-calculate dimension:

arr.reshape(4, -1)  # 4 rows, 3 columns (auto)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped 3D:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Random float between 0-1
rand_float = np.random.rand(3,3)
print(rand_float)

# Random integers between 0-10
rand_int = np.random.randint(0, 10, (2,4))
print(rand_int)

# Normal distribution
rand_norm = np.random.randn(3,3)
print(rand_norm)


# rand() →5edw451222

[[0.59835323 0.82875674 0.94368251]
 [0.80152067 0.19218513 0.22177006]
 [0.6141196  0.22755813 0.49660839]]
[[6 7 7 5]
 [0 5 9 9]]
[[-0.57731862  1.82935803 -0.45616949]
 [-0.41439746 -0.52496737  0.39395593]
 [-0.64628203 -0.92152388 -1.04507413]]


In [23]:
arr = np.array([1, 2, 3, 4, 5])

print("Mean:", arr.mean())        # 3.0
print("Median:", np.median(arr))  # 3.0
print("Std:", arr.std())          # 1.4142


Mean: 3.0
Median: 3.0
Std: 1.4142135623730951


In [24]:
arr2d = np.array([[1,2,3],[4,5,6]])
print("Mean axis=0:", arr2d.mean(axis=0))  # columns
print("Mean axis=1:", arr2d.mean(axis=1))  # rows


Mean axis=0: [2.5 3.5 4.5]
Mean axis=1: [2. 5.]


In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [4 10 18]
print(arr1 - arr2)  # [-3 -3 -3]
print(arr1 / arr2)  # [0.25 0.4 0.5]

# Functions are vectorized
print(np.sin(arr1))
print(np.sqrt(arr2))


[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[0.84147098 0.90929743 0.14112001]
[2.         2.23606798 2.44948974]


In [26]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Using @ operator
C = A @ B
print(C)

# Using np.dot()
D = np.dot(A, B)
print(D)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
arr = np.array([1,2,3,4,5,6])
mask = arr > 3

print("Mask:", mask)         # [False False False True True True]
print("Filtered:", arr[mask]) # [4 5 6]


Mask: [False False False  True  True  True]
Filtered: [4 5 6]


In [28]:
arr = np.array([1,2,3,4,5])
arr[arr > 3] = 99
print(arr)  # [1 2 3 99 99]


[ 1  2  3 99 99]


In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Vertical stack (rows)
vstack = np.vstack((a,b))
print("Vstack:\n", vstack)

# Horizontal stack (columns)
hstack = np.hstack((a,b))
print("Hstack:\n", hstack)


Vstack:
 [[1 2 3]
 [4 5 6]]
Hstack:
 [1 2 3 4 5 6]


In [30]:
arr = np.arange(10)
split_arr = np.array_split(arr, 3)
print(split_arr)  # 3 arrays


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [33]:
arr2d = np.array([[1,2,3],[4,5,6]])
flat = arr2d.flatten()
# print(flat)  # [1 2 3 4 5 6]

# Alternatively
flat2 = arr2d.ravel()  # returns view (faster)
print(flat2)  # [1 2 3 4 5 6]



[1 2 3 4 5 6]


In [3]:
import numpy as np

arr = np.arange(1_000_000)

result = arr * 2
print(result)

[      0       2       4 ... 1999994 1999996 1999998]
